// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable no-irregular-whitespace, @typescript-eslint/ban-types -- auto-generated by typesafe-i18n */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * A​p​p​ ​I​D
		 */
		appId: string
		/**
		 * A​p​p​ ​S​e​c​r​e​t
		 */
		appSecret: string
		/**
		 * 取​消
		 */
		cancel: string
		/**
		 * 保​存
		 */
		save: string
		/**
		 * 关​闭
		 */
		close: string
		/**
		 * 打​开
		 */
		open: string
		/**
		 * 下​载
		 */
		download: string
		/**
		 * 复​制​代​码
		 */
		copyCode: string
		/**
		 * 已​复​制
		 */
		copied: string
		/**
		 * 发​生​未​知​错​误​。
		 */
		unknownError: string
		/**
		 * 加​载​失​败
		 */
		loadingFailed: string
		/**
		 * 未​知​大​小
		 */
		unknownSize: string
	}
	presets: {
		/**
		 * 组​件​库​（​官​方​）
		 */
		componentsOfficial: string
		/**
		 * 组​件​库​（​第​三​方​）
		 */
		components: string
		/**
		 * x​d​b​ ​j​s​ ​库
		 */
		xdbjs: string
		/**
		 * 表​单​库
		 */
		forms: string
	}
	plugin: {
		/**
		 * 飞​书​资​源​库
		 */
		viewDisplayText: string
		commands: {
			/**
			 * 打​开​飞​书​资​源​库
			 */
			openView: string
			/**
			 * 测​试​连​接
			 */
			testConnection: string
			/**
			 * 刷​新​默​认​库
			 */
			refreshDefaultLibrary: string
		}
		ribbon: {
			/**
			 * 打​开​飞​书​资​源​库
			 */
			openView: string
		}
		notices: {
			/**
			 * 已​更​新​ ​{​l​a​b​e​l​}​ ​下​载​位​置
			 * @param {unknown} label
			 */
			downloadPathUpdated: RequiredParams<'label'>
			/**
			 * 连​接​成​功​，​共​读​取​ ​{​c​o​u​n​t​}​ ​条​记​录​。
			 * @param {unknown} count
			 */
			connectionSuccess: RequiredParams<'count'>
			/**
			 * 默​认​库​已​刷​新​。
			 */
			defaultLibraryRefreshed: string
			/**
			 * 已​跳​过​：​{​n​a​m​e​}
			 * @param {unknown} name
			 */
			skippedFile: RequiredParams<'name'>
			/**
			 * 已​下​载​：​{​n​a​m​e​}
			 * @param {unknown} name
			 */
			downloadedFile: RequiredParams<'name'>
		}
		errors: {
			/**
			 * 注​册​库​视​图​失​败​：​{​m​e​s​s​a​g​e​}
			 * @param {unknown} message
			 */
			registerLibraryView: RequiredParams<'message'>
			/**
			 * 无​法​从​内​置​知​识​库​链​接​解​析​数​据​表​ ​I​D​。
			 */
			cannotParseTableId: string
			/**
			 * u​s​e​S​e​t​t​i​n​g​s​S​t​o​r​e​ ​必​须​在​ ​S​e​t​t​i​n​g​s​P​r​o​v​i​d​e​r​ ​中​使​用​。
			 */
			settingsStoreProviderMissing: string
		}
	}
	settings: {
		/**
		 * 飞​书​库​配​置
		 */
		title: string
		/**
		 * 下​载​目​录
		 */
		downloadPathGroupTitle: string
		/**
		 * 默​认​打​开​的​库
		 */
		defaultLibraryPreset: string
		tabs: {
			/**
			 * 常​规​设​置
			 */
			general: string
			/**
			 * 配​置​教​程
			 */
			guide: string
		}
		/**
		 * c​l​i​_​x​x​x
		 */
		appIdPlaceholder: string
		/**
		 * s​e​c​r​e​t
		 */
		appSecretPlaceholder: string
		/**
		 * F​e​i​s​h​u​D​o​w​n​l​o​a​d​s​/​c​o​m​p​o​n​e​n​t​s​-​o​f​f​i​c​i​a​l
		 */
		componentsOfficialPathPlaceholder: string
		/**
		 * F​e​i​s​h​u​D​o​w​n​l​o​a​d​s​/​x​d​b​j​s
		 */
		xdbjsPathPlaceholder: string
		/**
		 * F​e​i​s​h​u​D​o​w​n​l​o​a​d​s​/​c​o​m​p​o​n​e​n​t​s
		 */
		componentsPathPlaceholder: string
		/**
		 * F​e​i​s​h​u​D​o​w​n​l​o​a​d​s​/​f​o​r​m​s
		 */
		formsPathPlaceholder: string
		/**
		 * F​e​i​s​h​u​D​o​w​n​l​o​a​d​s​/​f​o​r​m​s​/​s​c​r​i​p​t​s
		 */
		formScriptsPathPlaceholder: string
		/**
		 * {​l​a​b​e​l​}​ ​下​载​目​录
		 * @param {unknown} label
		 */
		xdbjsDownloadPath: RequiredParams<'label'>
		/**
		 * {​l​a​b​e​l​}​ ​下​载​目​录
		 * @param {unknown} label
		 */
		componentsDownloadPath: RequiredParams<'label'>
		/**
		 * {​l​a​b​e​l​}​ ​c​f​o​r​m​ ​下​载​目​录
		 * @param {unknown} label
		 */
		formsCformDownloadPath: RequiredParams<'label'>
		/**
		 * {​l​a​b​e​l​}​ ​J​S​ ​下​载​目​录
		 * @param {unknown} label
		 */
		formsJsDownloadPath: RequiredParams<'label'>
		/**
		 * 同​步​按​钮​仅​用​于​和​「​c​o​m​p​o​n​e​n​t​s​」​「​f​o​r​m​-​f​l​o​w​」​插​件​中​的​设​置​保​持​一​致​，​并​非​强​制​，​你​也​可​以​按​自​己​的​需​要​修​改​这​个​目​录​。
		 */
		syncHint: string
		/**
		 * 同​步​ ​{​p​a​t​h​}
		 * @param {unknown} path
		 */
		syncTooltip: RequiredParams<'path'>
		notices: {
			/**
			 * 未​安​装​插​件​：​{​p​l​u​g​i​n​I​d​}
			 * @param {unknown} pluginId
			 */
			pluginNotInstalled: RequiredParams<'pluginId'>
			/**
			 * 插​件​未​启​用​：​{​p​l​u​g​i​n​I​d​}
			 * @param {unknown} pluginId
			 */
			pluginNotEnabled: RequiredParams<'pluginId'>
			/**
			 * 未​找​到​ ​{​p​l​u​g​i​n​I​d​}​.​{​s​e​t​t​i​n​g​K​e​y​}​ ​设​置
			 * @param {unknown} pluginId
			 * @param {unknown} settingKey
			 */
			settingNotFound: RequiredParams<'pluginId' | 'settingKey'>
			/**
			 * 已​同​步​ ​{​l​a​b​e​l​}
			 * @param {unknown} label
			 */
			synced: RequiredParams<'label'>
		}
	}
	view: {
		hero: {
			/**
			 * 打​开​知​识​库​链​接
			 */
			openWikiLink: string
			/**
			 * 我​要​投​稿
			 */
			contribute: string
		}
		actions: {
			/**
			 * 刷​新​当​前​库
			 */
			refreshCurrentLibrary: string
		}
		emptyState: {
			/**
			 * 当​前​库​暂​无​可​下​载​附​件
			 */
			title: string
			/**
			 * 可​以​先​刷​新​当​前​库​，​或​检​查​飞​书​表​格​内​是​否​存​在​附​件​字​段​。
			 */
			description: string
		}
		sort: {
			/**
			 * 最​近​更​新
			 */
			recentlyUpdated: string
			/**
			 * 最​早​更​新
			 */
			earliestUpdated: string
			/**
			 * 名​称​ ​A​-​Z
			 */
			titleAsc: string
			/**
			 * 名​称​ ​Z​-​A
			 */
			titleDesc: string
		}
		lightbox: {
			/**
			 * 关​闭
			 */
			close: string
		}
		/**
		 * {​c​o​u​n​t​}​ ​张​卡​片
		 * @param {unknown} count
		 */
		fileCount: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​ ​个​文​件
		 * @param {unknown} count
		 */
		attachmentCount: RequiredParams<'count'>
	}
	setupGuide: {
		/**
		 * 先​完​成​飞​书​应​用​配​置
		 */
		title: string
		/**
		 * 权​限​ ​J​S​O​N
		 */
		permissionJsonTitle: string
		/**
		 * 权​限​ ​J​S​O​N​ ​已​复​制
		 */
		copySuccess: string
		/**
		 * 复​制​失​败​，​请​手​动​复​制​ ​J​S​O​N​。
		 */
		copyFailed: string
		/**
		 * 完​成​后​回​到​设​置​页​填​写​ ​A​p​p​ ​I​D​ ​和​ ​A​p​p​ ​S​e​c​r​e​t​，​再​刷​新​当​前​库​。
		 */
		finishHint: string
		steps: {
			/**
			 * 打​开
			 */
			openBeforeLink: string
			/**
			 * 飞​书​开​放​平​台
			 */
			openLinkLabel: string
			/**
			 * ，​登​录​后​创​建​一​个​自​建​应​用​，​获​取​ ​A​p​p​ ​I​D​ ​和​ ​A​p​p​ ​S​e​c​r​e​t​。
			 */
			openAfterLink: string
			/**
			 * 应​用​名​称​建​议​：​"​C​o​m​p​o​n​e​n​t​s​ ​F​e​i​s​h​u​ ​D​o​w​n​l​o​a​d​e​r​"​。
			 */
			appNameSuggestion: string
			/**
			 * 应​用​描​述​建​议​：​"​用​于​在​ ​O​b​s​i​d​i​a​n​ ​中​下​载​飞​书​ ​C​o​m​p​o​n​e​n​t​s​ ​库​"​。
			 */
			appDescriptionSuggestion: string
			/**
			 * 进​入​应​用​，​点​击​权​限​管​理​，​复​制​下​列​ ​J​S​O​N​ ​批​量​导​入​。
			 */
			importPermissions: string
			/**
			 * 发​布​应​用​版​本​，​点​击​凭​证​与​管​理​信​息​，​复​制​ ​A​p​p​ ​I​D​ ​和​ ​A​p​p​ ​S​e​c​r​e​t​。
			 */
			publishAndCopySecrets: string
		}
	}
	modals: {
		downloadProgress: {
			/**
			 * 下​载​进​度
			 */
			title: string
			/**
			 * 准​备​开​始​…
			 */
			preparing: string
			/**
			 * 检​查​下​载​目​标​.​.​.
			 */
			checkingTarget: string
			/**
			 * 等​待​选​择​同​名​文​件​处​理​方​式​.​.​.
			 */
			waitingConflictChoice: string
			/**
			 * 获​取​飞​书​访​问​凭​证​.​.​.
			 */
			fetchingAccessToken: string
			/**
			 * 下​载​文​件​内​容​.​.​.
			 */
			downloadingContent: string
			/**
			 * 写​入​ ​O​b​s​i​d​i​a​n​ ​仓​库​.​.​.
			 */
			writingVault: string
			/**
			 * 已​跳​过​同​名​文​件​。
			 */
			skippedConflict: string
			/**
			 * 下​载​完​成​。
			 */
			completed: string
		}
		overwriteMode: {
			/**
			 * 发​现​同​名​文​件
			 */
			title: string
			/**
			 * 目​标​位​置​已​存​在​同​名​文​件​：​{​f​i​l​e​N​a​m​e​}
			 * @param {unknown} fileName
			 */
			message: RequiredParams<'fileName'>
			/**
			 * 跳​过
			 */
			skip: string
			/**
			 * 重​命​名​保​存
			 */
			renameSave: string
			/**
			 * 覆​盖
			 */
			overwrite: string
		}
		downloadPath: {
			/**
			 * 修​改​ ​{​l​a​b​e​l​}​ ​下​载​位​置
			 * @param {unknown} label
			 */
			title: RequiredParams<'label'>
			/**
			 * 设​置​ ​{​l​a​b​e​l​}​ ​库​文​件​的​下​载​目​录​。
			 * @param {unknown} label
			 */
			message: RequiredParams<'label'>
			/**
			 * 下​载​目​录
			 */
			primaryName: string
			/**
			 * 路​径​相​对​于​当​前​ ​O​b​s​i​d​i​a​n​ ​仓​库​根​目​录
			 */
			primaryDesc: string
			/**
			 * 脚​本​下​载​目​录
			 */
			secondaryName: string
			/**
			 * 表​单​库​中​的​ ​.​j​s​ ​文​件​会​保​存​到​这​里
			 */
			secondaryDesc: string
			/**
			 * 下​载​目​录​不​能​为​空
			 */
			primaryRequired: string
			/**
			 * 脚​本​下​载​目​录​不​能​为​空
			 */
			secondaryRequired: string
		}
	}
	feishu: {
		errors: {
			/**
			 * 缺​少​ ​A​p​p​ ​I​D​ ​或​ ​A​p​p​ ​S​e​c​r​e​t​。
			 */
			missingAppCredentials: string
			/**
			 * 获​取​租​户​访​问​令​牌​失​败​：​{​r​e​a​s​o​n​}
			 * @param {unknown} reason
			 */
			failedTenantToken: RequiredParams<'reason'>
			/**
			 * 无​效​的​知​识​库​链​接​。
			 */
			invalidWikiUrl: string
			/**
			 * 无​法​从​知​识​库​链​接​解​析​ ​w​i​k​i​ ​节​点​ ​t​o​k​e​n​。
			 */
			cannotParseWikiNodeToken: string
			/**
			 * 解​析​ ​w​i​k​i​ ​节​点​失​败​：​{​r​e​a​s​o​n​}
			 * @param {unknown} reason
			 */
			failedResolveWikiNode: RequiredParams<'reason'>
			/**
			 * 目​标​ ​w​i​k​i​ ​节​点​不​是​多​维​表​格​，​当​前​类​型​：​{​o​b​j​T​y​p​e​}
			 * @param {unknown} objType
			 */
			targetNotBitable: RequiredParams<'objType'>
			/**
			 * 缺​少​ ​t​a​b​l​e​I​d​。
			 */
			missingTableId: string
			/**
			 * 查​询​记​录​失​败​：​{​r​e​a​s​o​n​}
			 * @param {unknown} reason
			 */
			failedSearchRecords: RequiredParams<'reason'>
			/**
			 * 附​件​ ​{​n​a​m​e​}​ ​不​包​含​可​下​载​链​接​。
			 * @param {unknown} name
			 */
			missingAttachmentUrl: RequiredParams<'name'>
			/**
			 * 下​载​附​件​失​败​：​H​T​T​P​ ​{​s​t​a​t​u​s​}
			 * @param {unknown} status
			 */
			failedDownloadAttachment: RequiredParams<'status'>
		}
	}
	record: {
		/**
		 * 记​录​ ​{​r​e​c​o​r​d​I​d​}
		 * @param {unknown} recordId
		 */
		fallbackTitle: RequiredParams<'recordId'>
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * App ID
		 */
		appId: () => LocalizedString
		/**
		 * App Secret
		 */
		appSecret: () => LocalizedString
		/**
		 * 取消
		 */
		cancel: () => LocalizedString
		/**
		 * 保存
		 */
		save: () => LocalizedString
		/**
		 * 关闭
		 */
		close: () => LocalizedString
		/**
		 * 打开
		 */
		open: () => LocalizedString
		/**
		 * 下载
		 */
		download: () => LocalizedString
		/**
		 * 复制代码
		 */
		copyCode: () => LocalizedString
		/**
		 * 已复制
		 */
		copied: () => LocalizedString
		/**
		 * 发生未知错误。
		 */
		unknownError: () => LocalizedString
		/**
		 * 加载失败
		 */
		loadingFailed: () => LocalizedString
		/**
		 * 未知大小
		 */
		unknownSize: () => LocalizedString
	}
	presets: {
		/**
		 * 组件库（官方）
		 */
		componentsOfficial: () => LocalizedString
		/**
		 * 组件库（第三方）
		 */
		components: () => LocalizedString
		/**
		 * xdb js 库
		 */
		xdbjs: () => LocalizedString
		/**
		 * 表单库
		 */
		forms: () => LocalizedString
	}
	plugin: {
		/**
		 * 飞书资源库
		 */
		viewDisplayText: () => LocalizedString
		commands: {
			/**
			 * 打开飞书资源库
			 */
			openView: () => LocalizedString
			/**
			 * 测试连接
			 */
			testConnection: () => LocalizedString
			/**
			 * 刷新默认库
			 */
			refreshDefaultLibrary: () => LocalizedString
		}
		ribbon: {
			/**
			 * 打开飞书资源库
			 */
			openView: () => LocalizedString
		}
		notices: {
			/**
			 * 已更新 {label} 下载位置
			 */
			downloadPathUpdated: (arg: { label: unknown }) => LocalizedString
			/**
			 * 连接成功，共读取 {count} 条记录。
			 */
			connectionSuccess: (arg: { count: unknown }) => LocalizedString
			/**
			 * 默认库已刷新。
			 */
			defaultLibraryRefreshed: () => LocalizedString
			/**
			 * 已跳过：{name}
			 */
			skippedFile: (arg: { name: unknown }) => LocalizedString
			/**
			 * 已下载：{name}
			 */
			downloadedFile: (arg: { name: unknown }) => LocalizedString
		}
		errors: {
			/**
			 * 注册库视图失败：{message}
			 */
			registerLibraryView: (arg: { message: unknown }) => LocalizedString
			/**
			 * 无法从内置知识库链接解析数据表 ID。
			 */
			cannotParseTableId: () => LocalizedString
			/**
			 * useSettingsStore 必须在 SettingsProvider 中使用。
			 */
			settingsStoreProviderMissing: () => LocalizedString
		}
	}
	settings: {
		/**
		 * 飞书库配置
		 */
		title: () => LocalizedString
		/**
		 * 下载目录
		 */
		downloadPathGroupTitle: () => LocalizedString
		/**
		 * 默认打开的库
		 */
		defaultLibraryPreset: () => LocalizedString
		tabs: {
			/**
			 * 常规设置
			 */
			general: () => LocalizedString
			/**
			 * 配置教程
			 */
			guide: () => LocalizedString
		}
		/**
		 * cli_xxx
		 */
		appIdPlaceholder: () => LocalizedString
		/**
		 * secret
		 */
		appSecretPlaceholder: () => LocalizedString
		/**
		 * FeishuDownloads/components-official
		 */
		componentsOfficialPathPlaceholder: () => LocalizedString
		/**
		 * FeishuDownloads/xdbjs
		 */
		xdbjsPathPlaceholder: () => LocalizedString
		/**
		 * FeishuDownloads/components
		 */
		componentsPathPlaceholder: () => LocalizedString
		/**
		 * FeishuDownloads/forms
		 */
		formsPathPlaceholder: () => LocalizedString
		/**
		 * FeishuDownloads/forms/scripts
		 */
		formScriptsPathPlaceholder: () => LocalizedString
		/**
		 * {label} 下载目录
		 */
		xdbjsDownloadPath: (arg: { label: unknown }) => LocalizedString
		/**
		 * {label} 下载目录
		 */
		componentsDownloadPath: (arg: { label: unknown }) => LocalizedString
		/**
		 * {label} cform 下载目录
		 */
		formsCformDownloadPath: (arg: { label: unknown }) => LocalizedString
		/**
		 * {label} JS 下载目录
		 */
		formsJsDownloadPath: (arg: { label: unknown }) => LocalizedString
		/**
		 * 同步按钮仅用于和「components」「form-flow」插件中的设置保持一致，并非强制，你也可以按自己的需要修改这个目录。
		 */
		syncHint: () => LocalizedString
		/**
		 * 同步 {path}
		 */
		syncTooltip: (arg: { path: unknown }) => LocalizedString
		notices: {
			/**
			 * 未安装插件：{pluginId}
			 */
			pluginNotInstalled: (arg: { pluginId: unknown }) => LocalizedString
			/**
			 * 插件未启用：{pluginId}
			 */
			pluginNotEnabled: (arg: { pluginId: unknown }) => LocalizedString
			/**
			 * 未找到 {pluginId}.{settingKey} 设置
			 */
			settingNotFound: (arg: { pluginId: unknown, settingKey: unknown }) => LocalizedString
			/**
			 * 已同步 {label}
			 */
			synced: (arg: { label: unknown }) => LocalizedString
		}
	}
	view: {
		hero: {
			/**
			 * 打开知识库链接
			 */
			openWikiLink: () => LocalizedString
			/**
			 * 我要投稿
			 */
			contribute: () => LocalizedString
		}
		actions: {
			/**
			 * 刷新当前库
			 */
			refreshCurrentLibrary: () => LocalizedString
		}
		emptyState: {
			/**
			 * 当前库暂无可下载附件
			 */
			title: () => LocalizedString
			/**
			 * 可以先刷新当前库，或检查飞书表格内是否存在附件字段。
			 */
			description: () => LocalizedString
		}
		sort: {
			/**
			 * 最近更新
			 */
			recentlyUpdated: () => LocalizedString
			/**
			 * 最早更新
			 */
			earliestUpdated: () => LocalizedString
			/**
			 * 名称 A-Z
			 */
			titleAsc: () => LocalizedString
			/**
			 * 名称 Z-A
			 */
			titleDesc: () => LocalizedString
		}
		lightbox: {
			/**
			 * 关闭
			 */
			close: () => LocalizedString
		}
		/**
		 * {count} 张卡片
		 */
		fileCount: (arg: { count: unknown }) => LocalizedString
		/**
		 * {count} 个文件
		 */
		attachmentCount: (arg: { count: unknown }) => LocalizedString
	}
	setupGuide: {
		/**
		 * 先完成飞书应用配置
		 */
		title: () => LocalizedString
		/**
		 * 权限 JSON
		 */
		permissionJsonTitle: () => LocalizedString
		/**
		 * 权限 JSON 已复制
		 */
		copySuccess: () => LocalizedString
		/**
		 * 复制失败，请手动复制 JSON。
		 */
		copyFailed: () => LocalizedString
		/**
		 * 完成后回到设置页填写 App ID 和 App Secret，再刷新当前库。
		 */
		finishHint: () => LocalizedString
		steps: {
			/**
			 * 打开
			 */
			openBeforeLink: () => LocalizedString
			/**
			 * 飞书开放平台
			 */
			openLinkLabel: () => LocalizedString
			/**
			 * ，登录后创建一个自建应用，获取 App ID 和 App Secret。
			 */
			openAfterLink: () => LocalizedString
			/**
			 * 应用名称建议："Components Feishu Downloader"。
			 */
			appNameSuggestion: () => LocalizedString
			/**
			 * 应用描述建议："用于在 Obsidian 中下载飞书 Components 库"。
			 */
			appDescriptionSuggestion: () => LocalizedString
			/**
			 * 进入应用，点击权限管理，复制下列 JSON 批量导入。
			 */
			importPermissions: () => LocalizedString
			/**
			 * 发布应用版本，点击凭证与管理信息，复制 App ID 和 App Secret。
			 */
			publishAndCopySecrets: () => LocalizedString
		}
	}
	modals: {
		downloadProgress: {
			/**
			 * 下载进度
			 */
			title: () => LocalizedString
			/**
			 * 准备开始…
			 */
			preparing: () => LocalizedString
			/**
			 * 检查下载目标...
			 */
			checkingTarget: () => LocalizedString
			/**
			 * 等待选择同名文件处理方式...
			 */
			waitingConflictChoice: () => LocalizedString
			/**
			 * 获取飞书访问凭证...
			 */
			fetchingAccessToken: () => LocalizedString
			/**
			 * 下载文件内容...
			 */
			downloadingContent: () => LocalizedString
			/**
			 * 写入 Obsidian 仓库...
			 */
			writingVault: () => LocalizedString
			/**
			 * 已跳过同名文件。
			 */
			skippedConflict: () => LocalizedString
			/**
			 * 下载完成。
			 */
			completed: () => LocalizedString
		}
		overwriteMode: {
			/**
			 * 发现同名文件
			 */
			title: () => LocalizedString
			/**
			 * 目标位置已存在同名文件：{fileName}
			 */
			message: (arg: { fileName: unknown }) => LocalizedString
			/**
			 * 跳过
			 */
			skip: () => LocalizedString
			/**
			 * 重命名保存
			 */
			renameSave: () => LocalizedString
			/**
			 * 覆盖
			 */
			overwrite: () => LocalizedString
		}
		downloadPath: {
			/**
			 * 修改 {label} 下载位置
			 */
			title: (arg: { label: unknown }) => LocalizedString
			/**
			 * 设置 {label} 库文件的下载目录。
			 */
			message: (arg: { label: unknown }) => LocalizedString
			/**
			 * 下载目录
			 */
			primaryName: () => LocalizedString
			/**
			 * 路径相对于当前 Obsidian 仓库根目录
			 */
			primaryDesc: () => LocalizedString
			/**
			 * 脚本下载目录
			 */
			secondaryName: () => LocalizedString
			/**
			 * 表单库中的 .js 文件会保存到这里
			 */
			secondaryDesc: () => LocalizedString
			/**
			 * 下载目录不能为空
			 */
			primaryRequired: () => LocalizedString
			/**
			 * 脚本下载目录不能为空
			 */
			secondaryRequired: () => LocalizedString
		}
	}
	feishu: {
		errors: {
			/**
			 * 缺少 App ID 或 App Secret。
			 */
			missingAppCredentials: () => LocalizedString
			/**
			 * 获取租户访问令牌失败：{reason}
			 */
			failedTenantToken: (arg: { reason: unknown }) => LocalizedString
			/**
			 * 无效的知识库链接。
			 */
			invalidWikiUrl: () => LocalizedString
			/**
			 * 无法从知识库链接解析 wiki 节点 token。
			 */
			cannotParseWikiNodeToken: () => LocalizedString
			/**
			 * 解析 wiki 节点失败：{reason}
			 */
			failedResolveWikiNode: (arg: { reason: unknown }) => LocalizedString
			/**
			 * 目标 wiki 节点不是多维表格，当前类型：{objType}
			 */
			targetNotBitable: (arg: { objType: unknown }) => LocalizedString
			/**
			 * 缺少 tableId。
			 */
			missingTableId: () => LocalizedString
			/**
			 * 查询记录失败：{reason}
			 */
			failedSearchRecords: (arg: { reason: unknown }) => LocalizedString
			/**
			 * 附件 {name} 不包含可下载链接。
			 */
			missingAttachmentUrl: (arg: { name: unknown }) => LocalizedString
			/**
			 * 下载附件失败：HTTP {status}
			 */
			failedDownloadAttachment: (arg: { status: unknown }) => LocalizedString
		}
	}
	record: {
		/**
		 * 记录 {recordId}
		 */
		fallbackTitle: (arg: { recordId: unknown }) => LocalizedString
	}
}

export type Formatters = {}
